service: chat-wit
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: default

functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true